apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  namespace: media-dev
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - plex-dev.factotumsoftware.com
      secretName: media-dev-issuer-key
  - hosts:
    - pb-dev.factotumsoftware.com
      secretName: mb-dev-issuer-key
  rules:
  - host: plex-dev.factotumsoftware.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: media-catalog-service
            port: 
              number: 80
  - host: pb-dev.factotumsoftware.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: media-storage-service
            port: 
              number: 8080

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  namespace: media-prod
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - plex.factotumsoftware.com
      secretName: media-issuer-key
  - hosts:
    - pb.factotumsoftware.com
      secretName: mb-issuer-key
  rules:
  - host: plex.factotumsoftware.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: media-catalog-service
            port: 
              number: 80
  - host: pb.factotumsoftware.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: media-storage-service
            port: 
              number: 8080