apiVersion: v1
kind: Service
metadata:
  name: movie-storage-service
spec:
  selector:
    app: movie-storage
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-storage
  labels: 
    app: movie-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-storage
  template:
    metadata:
      labels:
        app: movie-storage
    spec:
      containers:
        - name: movie-storage
          image: repository.factotumsoftware.com/plex-backend:0.0.7-SNAPSHOT
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: plex-mysql-service
spec:
  selector:
    app: mysql
  clusterIP: None
  ports:
  - port: 3306
      
---

kind: Endpoints
apiVersion: v1
metadata:
  name: plex-mysql-service
subsets:
  - addresses:
        - ip: 172.16.0.7
    ports:
      - port: 3306
        name: plex-mysql-service



    
