apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-dev-certificate
  namespace: mm-dev
spec:
  dnsNames:
    - moneymaker-dev.factotumsoftware.com
  secretName: mm-dev-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer

--- 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-certificate
  namespace: mm-prod
spec:
  dnsNames:
    - moneymaker.factotumsoftware.com
  secretName: mm-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer

--- 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-gateway-dev-certificate
  namespace: mm-dev
spec:
  dnsNames:
    - mm-gateway-dev.factotumsoftware.com
  secretName: mm-gateway-dev-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-gateway-certificate
  namespace: mm-prod
spec:
  dnsNames:
    - mm-gateway.factotumsoftware.com
  secretName: mm-gateway-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer

--- 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-admin-dev-certificate
  namespace: mm-dev
spec:
  dnsNames:
    - mm-admin-dev.factotumsoftware.com
  secretName: mm-admin-dev-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-admin-certificate
  namespace: mm-prod
spec:
  dnsNames:
    - mm-admin.factotumsoftware.com
  secretName: mm-admin-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer