apiVersion: v1
kind: Service
metadata:
  name: moneymaker-gateway-service
spec:
  selector:
    app: moneymaker-gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneymaker-gateway
  labels:
    app: moneymaker-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneymaker-gateway
  template:
    metadata:
      labels:
        app: moneymaker-gateway
    spec:
      containers:
        - name: moneymaker-gateway
          image: repository.factotumsoftware.com/gateway:0.0.1-SNAPSHOT
          ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: moneymaker-admin-service
spec:
  selector:
    app: moneymaker-admin
  type: Loadbalancer
  ports:
    - protoco: TCP
      port: 8079
      targetPort: 8079

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneymaker-admin
  labels:
    app: moneymaker-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneymaker-admin
  template:
    metadata:
      labels:
        app: moneymaker-admin
    spec:
      containers:
        - name: moneymaker-admin
          image: repository.factotumsoftware.com/garnet-admin:0.0.1-SNAPSHOT
          ports:
          - containerPort: 8079
      imagePullSecrets:
      - name: regcred