apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: factotum-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: test@gmail.com
    privateKeySecretRef:
      name: factotum-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx
