apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: factotum-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # server: https://acme-v02.api.letsencrypt.org/directory
    email: test@email.com
    privateKeySecretRef:
      name: factotum-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx